version: '3.8'

services:
  ia-api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: ia-api
    restart: unless-stopped

    ports:
      - "8052:8000"

    environment:
      OLLAMA_API_URL: "http://ollama:11434/api/generate"
      ROOT_PATH: ""

    networks:
      - ollama

networks:
  ollama:
    external: true
